name: pedant
version: 0.1.0.0
synopsis: A Math language for Dimensional Analysis
description: See README at <https://github.com/sol/hpack#readme>
maintainer: Sam Nolan <samnolan555@gmail.com>
github: Hazelfire/pedant
category: Economics
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - lsp
  - filepath
  - lsp-types
  - lens
  - parser-combinators
  - megaparsec
  - ordered-containers
  - mtl
  - random
  - lens
  - containers
  - text
  - hslogger

data-files:
  - "**/*.ped"

library:
  source-dirs: src
  exposed-modules:
    - Pedant

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - pedant

tests:
  tests:
    main: Main.hs
    source-dirs: 
      - test
      - src
    dependencies:
      - hspec